import { ChurchSettings } from './types';

export const initialChurchData: ChurchSettings = {
  churchName: 'Igreja Catedral de Amor e Fé',
  churchMotto: 'Um lugar de fé, amor, comunhão e transformação.',
  churchAbout:
    'A Catedral de Amor e Fé é uma comunidade cristã viva, contemporânea e acolhedora, dedicada a proclamar o Evangelho de Jesus Cristo, transformar vidas através da Palavra e manifestar o amor prático em nossa sociedade.',
  phone: '+244 923 847 110',
  whatsappNumber: '+244923847110',
  whatsappMessage: 'Olá, gostaria de saber mais informações sobre a atividade da Igreja Catedral de Amor e Fé!',
  email: 'contacto@catedraldeamorefe.org',
  address: 'Avenida Principal da Fé, nº 1250, Bairro Central',
  cityCountry: 'Luanda, Angola',
  worshipSchedule: [
    { day: 'Quarta-feira', time: '19h00', name: 'Culto de Oração, Fé e Doutrina' },
    { day: 'Sábado', time: '16h30', name: 'Conexão Jovem & Juventude Catedral' },
    { day: 'Domingo (Manhã)', time: '08h30', name: 'Culto de Celebração & Famílias (1º Turno)' },
    { day: 'Domingo (Noite)', time: '18h00', name: 'Culto de Celebração & Impacto (2º Turno)' },
  ],
  currentActivity: {
    id: 'act-2026-conferencia-renovo',
    name: 'GRANDE CONFERÊNCIA RENOVO & IMPACTO 2026',
    subtitle: 'Um momento de fé, comunhão, transformação e celebração.',
    theme: '«Edificados na Fé, Transbordando em Amor e Ação» (Colossenses 2:6-7)',
    date: '2026-09-18T18:00:00', // Upcoming event date
    formattedDate: '18 a 21 de Setembro de 2026',
    time: '18h00 às 21h30 (Sábado e Domingo com sessões especiais a partir das 16h00)',
    location: 'Templo Central — Auditório Principal da Catedral',
    address: 'Av. Principal da Fé, nº 1250, Luanda',
    organization: 'Conselho Pastoral, Ministério de Louvor & Juventude Catedral',
    targetAudience: 'Famílias, Jovens, Líderes comunitários e toda a comunidade de fé',
    goal: 'Promover despertamento espiritual profundo, fortalecimento das famílias, capacitação da liderança jovem e mobilização social com entrega de donativos a comunidades em vulnerabilidade.',
    importantNotes:
      'Entrada totalmente livre e gratuita. Espaço Kids especial disponível para crianças de 2 a 11 anos. Transmissão simultânea em alta definição pelos canais oficiais.',
    heroImage: 'https://images.unsplash.com/photo-1519834785169-98be25ec3f84?auto=format&fit=crop&w=1920&q=85',
    heroVideo: 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
    videoPromoUrl: 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
    badge: 'Evento Especial do Ano',
    status: 'upcoming',
  },
  highlights: [
    {
      id: 'hl-1',
      title: 'Momento de Louvor & Adoração',
      subtitle: 'Uma atmosfera de exaltação a Deus',
      description:
        'Cânticos congregacionais vibrantes, orquestra, coral jovem e momentos íntimos de adoração que tocam profundamente o coração e renovam a alma.',
      imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=900&q=80',
      iconName: 'Music',
      verse: '«Cantai ao Senhor um cântico novo, cantai ao Senhor toda a terra.» — Sl 96:1',
    },
    {
      id: 'hl-2',
      title: 'Momento da Palavra',
      subtitle: 'Uma mensagem viva e edificante',
      description:
        'Ministrações profundas e práticas baseadas nas Escrituras Sagradas para fortalecer a fé, direcionar decisões e gerar maturidade espiritual.',
      imageUrl: 'https://images.unsplash.com/photo-1504052434569-70ad5836ab65?auto=format&fit=crop&w=900&q=80',
      iconName: 'BookOpen',
      verse: '«A tua palavra é lâmpada para os meus pés e luz para o meu caminho.» — Sl 119:105',
    },
    {
      id: 'hl-3',
      title: 'Momento de Comunhão',
      subtitle: 'Juntos como uma grande família',
      description:
        'Espaço acolhedor de integração, partilha fraterna, abraços sinceros e fortalecimento de laços de amizade e irmandade no amor de Cristo.',
      imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=900&q=80',
      iconName: 'HeartHandshake',
      verse: '«Quão bom e suave é que os irmãos vivam em união!» — Sl 133:1',
    },
    {
      id: 'hl-4',
      title: 'Momento de Oração & Intercessão',
      subtitle: 'Clamor de fé e cura espiritual',
      description:
        'Períodos de intercessão individual e coletiva pelas famílias, pelos enfermos, pela juventude e pelo futuro da nossa nação.',
      imageUrl: 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&w=900&q=80',
      iconName: 'Flame',
      verse: '«A oração feita por um justo pode muito em seus efeitos.» — Tg 5:16',
    },
    {
      id: 'hl-5',
      title: 'Impacto Social & Solidariedade',
      subtitle: 'O Evangelho em ação na comunidade',
      description:
        'Arrecadação de alimentos não perecíveis, agasalhos e materiais escolares para distribuição em centros de acolhimento parceiros.',
      imageUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=900&q=80',
      iconName: 'Gift',
      verse: '«Não amemos de palavra nem de boca, mas por obras e em verdade.» — 1 Jo 3:18',
    },
  ],
  photos: [
    {
      id: 'p-1',
      title: 'Coral & Ministério de Louvor',
      description: 'Celebração com vozes unidas em louvor e profunda entrega espiritual no altar principal.',
      imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
      category: 'Louvor',
      date: 'Atividade Recente',
      photographer: 'Comunicação Catedral',
    },
    {
      id: 'p-2',
      title: 'Juventude em Ação',
      description: 'Centenas de jovens reunidos com energia, adoração e propósito no grande auditório.',
      imageUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80',
      category: 'Juventude',
      date: 'Atividade Recente',
      photographer: 'Juventude Conectados',
    },
    {
      id: 'p-3',
      title: 'Ministração da Palavra',
      description: 'O Pastor Presidente compartilhando ensinamento bíblico para edificar toda a congregação.',
      imageUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?auto=format&fit=crop&w=1200&q=80',
      category: 'Palavra',
      date: 'Atividade Recente',
      photographer: 'Mídia Oficial',
    },
    {
      id: 'p-4',
      title: 'Abraço de Comunhão Fraterna',
      description: 'Membros e visitantes celebrando a união e a paz no término da grande celebração.',
      imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80',
      category: 'Comunhão',
      date: 'Atividade Recente',
      photographer: 'Comunicação Catedral',
    },
    {
      id: 'p-5',
      title: 'Famílias no Altar de Oração',
      description: 'Momento marcante de intercessão e bênção sacerdotal sobre os lares e crianças.',
      imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1200&q=80',
      category: 'Famílias',
      date: 'Atividade Recente',
      photographer: 'Mídia Oficial',
    },
    {
      id: 'p-6',
      title: 'Banda Instrumental ao Vivo',
      description: 'Músicos dedicando talentos e excelência sonora em adoração contínua ao Senhor.',
      imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
      category: 'Louvor',
      date: 'Atividade Recente',
      photographer: 'Comunicação Catedral',
    },
    {
      id: 'p-7',
      title: 'Espaço Infantil & Ministério Kids',
      description: 'Crianças aprendendo histórias bíblicas com amor, dinâmicas e alegria.',
      imageUrl: 'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?auto=format&fit=crop&w=1200&q=80',
      category: 'Famílias',
      date: 'Atividade Recente',
      photographer: 'Catedral Kids',
    },
    {
      id: 'p-8',
      title: 'Noite de Testemunhos e Gratidão',
      description: 'Irmãos compartilhando vitórias, restaurações e milagres alcançados pela fé.',
      imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80',
      category: 'Comunhão',
      date: 'Atividade Recente',
      photographer: 'Mídia Oficial',
    },
  ],
  videos: [
    {
      id: 'v-1',
      title: 'Resumo Oficial da Última Conferência',
      description: 'Confira os momentos mais marcantes da nossa última grande concentração de fé e louvor.',
      thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=900&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/ScMzIvxBSi4',
      duration: '04:35 min',
      category: 'Destaques',
      date: 'Atividade Recente',
    },
    {
      id: 'v-2',
      title: 'Momento de Louvor: «Transborda em Nós»',
      description: 'Adoração ao vivo com o Coral Catedral e Ministério de Música durante o culto de domingo.',
      thumbnailUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=900&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/ScMzIvxBSi4',
      duration: '07:12 min',
      category: 'Louvor',
      date: 'Culto Especial',
    },
    {
      id: 'v-3',
      title: 'Trecho da Mensagem: «Fé para Vencer Gigantes»',
      description: 'Uma palavra viva pregada pelo Pastor Presidente sobre perseverança e confiança em Deus.',
      thumbnailUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/ScMzIvxBSi4',
      duration: '12:40 min',
      category: 'Palavra',
      date: 'Ministração',
    },
    {
      id: 'v-4',
      title: 'Ação Social: Transformando a Nossa Cidade',
      description: 'Documentário especial sobre as doações e apoio comunitário realizado pela Igreja.',
      thumbnailUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=900&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/ScMzIvxBSi4',
      duration: '05:50 min',
      category: 'Social',
      date: 'Projeto Amor Prático',
    },
  ],
  upcomingEvents: [
    {
      id: 'ev-1',
      title: 'Noite de Louvor & Adoração Profunda',
      category: 'Música & Espiritualidade',
      date: '10 de Outubro de 2026',
      time: '19h00',
      location: 'Auditório Principal',
      description: 'Uma noite dedicada integralmente a cânticos de adoração, oração contemplativa e gratidão.',
      fullDetails:
        'Participe com toda a sua família desta noite inesquecível de adoração com o Coral Catedral e convidados especiais. Entrada franca. Aberto a toda a comunidade.',
      imageUrl: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&w=800&q=80',
      speaker: 'Ministério de Louvor & Convidados',
      featured: true,
    },
    {
      id: 'ev-2',
      title: 'Encontro da Juventude «Conectados em Cristo»',
      category: 'Juventude',
      date: '24 de Outubro de 2026',
      time: '16h00',
      location: 'Espaço Jovem / Sala Polivalente',
      description: 'Dinâmicas, debate bíblico sobre dilemas da juventude contemporânea, música e comunhão.',
      fullDetails:
        'Voltado para adolescentes e jovens de 13 a 30 anos. Traga um amigo! Haverá momentos de louvor acústico, coffee break e palestras práticas.',
      imageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=800&q=80',
      speaker: 'Pastores de Juventude',
      featured: false,
    },
    {
      id: 'ev-3',
      title: 'Seminário de Fortalecimento das Famílias e Casais',
      category: 'Famílias',
      date: '07 de Novembro de 2026',
      time: '09h00 às 13h00',
      location: 'Auditório Principal',
      description: 'Princípios bíblicos e conselhos práticos para matrimônios saudáveis e criação de filhos.',
      fullDetails:
        'Um seminário com orientações valorosas para casais, pais e noivos. Inscrições abertas na secretaria da igreja e via WhatsApp.',
      imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80',
      speaker: 'Equipe de Aconselhamento Familiar',
      featured: false,
    },
    {
      id: 'ev-4',
      title: 'Grande Ação Solidária: Mãos de Amor & Fé',
      category: 'Ação Social',
      date: '21 de Novembro de 2026',
      time: '08h00 às 15h00',
      location: 'Comunidade do Bairro Esperança',
      description: 'Atendimento médico e odontológico gratuito, distribuição de cestas básicas e apoio a crianças.',
      fullDetails:
        'Mobilização geral de voluntários da igreja. Venha ser as mãos e pés de Jesus servindo ao próximo. Ponto de encontro no Templo Central.',
      imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80',
      speaker: 'Departamento de Ação Social',
      featured: true,
    },
  ],
  socialLinks: [
    {
      id: 'soc-instagram',
      platform: 'Instagram',
      name: 'Instagram Oficial',
      description: 'Acompanhe fotos em alta resolução, stories diários, reels de testemunhos e avisos.',
      handle: '@catedraldeamorefe',
      url: 'https://instagram.com',
      followers: 'Mais de 15.000 seguidores',
      badgeText: 'Mais Ativo',
    },
    {
      id: 'soc-youtube',
      platform: 'YouTube',
      name: 'Canal no YouTube',
      description: 'Assista a transmissões ao vivo de todos os cultos, pregações completas e clipes de louvor.',
      handle: 'Catedral de Amor e Fé TV',
      url: 'https://youtube.com',
      followers: 'Cultos ao vivo em Full HD',
      badgeText: 'Ao Vivo',
    },
    {
      id: 'soc-facebook',
      platform: 'Facebook',
      name: 'Página no Facebook',
      description: 'Fique por dentro de eventos, comunicados oficiais, reflexões pastorais e álbuns de fotos.',
      handle: 'fb.com/catedraldeamorefe',
      url: 'https://facebook.com',
      followers: 'Comunidade ativa',
      badgeText: 'Oficial',
    },
    {
      id: 'soc-whatsapp',
      platform: 'WhatsApp',
      name: 'Canal & Atendimento WhatsApp',
      description: 'Receba pedidos de oração, avisos semanais e fale diretamente com o conselho pastoral.',
      handle: '+244 923 847 110',
      url: 'https://wa.me/244923847110?text=Ol%C3%A1%2C%20gostaria%20de%20falar%20com%20a%20Igreja%20Catedral%20de%20Amor%20e%20F%C3%A9',
      followers: 'Atendimento Rápido',
      badgeText: 'Direto',
    },
  ],
  testimonies: [
    {
      id: 't-1',
      name: 'Irmã Madalena dos Santos',
      role: 'Membro da Congregação e Líder de Oração',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      content:
        'A última atividade foi um divisor de águas na vida da minha família. Chegamos sobrecarregados e saímos renovados pelo poder do amor de Deus e pelo acolhimento caloroso desta igreja.',
      activityName: 'Conferência de Fé & Avivamento',
      date: 'Membro há 4 anos',
    },
    {
      id: 't-2',
      name: 'Mateus Kanhanga',
      role: 'Líder da Juventude Catedral',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      content:
        'Ver tantos jovens de diferentes origens louvando com entusiasmo e encontrando um propósito genuíno em Cristo é a maior recompensa. Esta igreja respira comunhão e verdade.',
      activityName: 'Encontro Conexão Jovem',
      date: 'Juventude Catedral',
    },
    {
      id: 't-3',
      name: 'Dr. Afonso e Teresa Vunge',
      role: 'Casais com Propósito',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      content:
        'As palavras ministradas nesta casa têm sustentado o nosso casamento e orientado nossos filhos nos caminhos da honra e da fé. Um lugar onde nos sentimos verdadeiramente em família.',
      activityName: 'Seminário de Famílias',
      date: 'Membros da Catedral',
    },
  ],
  developedBy: {
    name: 'Baobá Universe',
    description: 'Soluções Digitais e Desenvolvimento Web de Alto Impacto',
    url: 'https://baobauniverse.com',
  },
};
